### Leitura dos dados

In [1]:
import numpy as np

In [2]:
data = np.loadtxt('preprocessed_Data.csv',delimiter=",")

In [3]:
prepared_data = []
for i in range(0,data.shape[0],30):
    prepared_data.append(data[i:i+30])
prepared_data = np.array(prepared_data)

In [4]:
prepared_data.shape

(285211, 30, 4)

## Construcao do modelo

In [5]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import TimeDistributed

In [6]:
def encoder(model):
    model.add(LSTM(15, activation='relu', return_sequences=True, input_shape=(prepared_data.shape[1], prepared_data.shape[2])))
    model.add(LSTM(10, activation='relu', return_sequences=True))
    model.add(LSTM(5, activation='relu', return_sequences=True))
    return model

def decoder(model):
    model.add(LSTM(5, activation='relu', return_sequences=True))
    model.add(LSTM(10, activation='relu', return_sequences=True))
    model.add(LSTM(15, activation='relu', return_sequences=True))
    model.add(TimeDistributed(Dense(4)))
    return model

### Execução do Modelo

In [7]:
with tensorflow.device("/cpu:0"):
    model = Sequential()
    enc_model = encoder(model)
    dec_model = decoder(enc_model)
    dec_model.compile(optimizer='SGD', loss='mse')
    # fit model
    dec_model.fit(prepared_data[:2000], prepared_data[:2000], epochs=10, verbose=1)

Train on 2000 samples
Epoch 1/10
2000/2000 [==============================] - 7s 4ms/sample - loss: 0.1117
Epoch 2/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0310
Epoch 3/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0114
Epoch 4/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0061
Epoch 5/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0044
Epoch 6/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0037
Epoch 7/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0034
Epoch 8/10
2000/2000 [==============================] - 3s 1ms/sample - loss: 0.0032
Epoch 9/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0030
Epoch 10/10
2000/2000 [==============================] - 2s 1ms/sample - loss: 0.0029


### Evaluation

In [8]:
# demonstrate prediction
x_input = prepared_data[0].reshape((1, prepared_data.shape[1], prepared_data.shape[2]))
yhat = dec_model.predict(x_input, verbose=0)
print(yhat)

[[[-0.02001473  0.47954226  0.067664    0.26846582]
  [ 0.00303602  0.54693985  0.10568883  0.3005962 ]
  [ 0.01998659  0.59969974  0.13681224  0.325618  ]
  [ 0.03241149  0.6408509   0.16204418  0.34510726]
  [ 0.04148334  0.67284954  0.18233563  0.36029157]
  [ 0.04807492  0.6976657   0.19854093  0.37212637]
  [ 0.05291086  0.7168497   0.21146266  0.38131517]
  [ 0.05646664  0.73164696  0.22173142  0.38843763]
  [ 0.05907453  0.743044    0.22985925  0.39395714]
  [ 0.06098168  0.751813    0.23627092  0.39823425]
  [ 0.0623716   0.75855494  0.24131472  0.40154907]
  [ 0.06338044  0.7637364   0.24527347  0.4041188 ]
  [ 0.06411827  0.76771176  0.24838205  0.4061235 ]
  [ 0.06465364  0.7707621   0.25081742  0.4076866 ]
  [ 0.06503701  0.7731046   0.252721    0.40890282]
  [ 0.06530744  0.77490646  0.2542069   0.40984732]
  [ 0.06549473  0.7762953   0.2553659   0.41057947]
  [ 0.06562138  0.77736855  0.25627008  0.41114604]
  [ 0.06570433  0.7782007   0.25697616  0.4115838 ]
  [ 0.065756

In [9]:
prepared_data[0]

array([[0.0570538 , 0.75224483, 0.23634978, 0.31873703],
       [0.05705375, 0.75224531, 0.23634978, 0.31873703],
       [0.05705376, 0.75224483, 0.23634978, 0.31873703],
       [0.05705376, 0.75224411, 0.23634978, 0.31873703],
       [0.05705367, 0.75224173, 0.23634978, 0.31873703],
       [0.05705357, 0.75223744, 0.23635691, 0.31873703],
       [0.05705355, 0.75223267, 0.23635691, 0.31873703],
       [0.05705343, 0.7522279 , 0.23637831, 0.31873703],
       [0.05705337, 0.75222385, 0.23640686, 0.31873703],
       [0.05705355, 0.75221956, 0.23644254, 0.31873703],
       [0.05705345, 0.7522167 , 0.23647822, 0.31873703],
       [0.05705349, 0.75221312, 0.2365139 , 0.31873703],
       [0.05705343, 0.75220954, 0.23654959, 0.31873703],
       [0.05705336, 0.75220621, 0.23658526, 0.31873703],
       [0.05705334, 0.75220311, 0.23662809, 0.31873703],
       [0.05705331, 0.75219905, 0.23666376, 0.31873703],
       [0.05705334, 0.75219643, 0.23669945, 0.31873703],
       [0.05705346, 0.75219238,

In [ ]:
yhat = dec_model.predict(prepared_data[:2000])

In [ ]:
def error_by_entry(y_real,y_pred):
    errors = []
    for real,pred in zip(y_real,y_pred):
        acc = 0
        for i,j in zip(real,pred):
            for k,l in zip(i,j):
                acc += abs(k-l)
        errors.append(acc)
    return errors

In [ ]:
errors = error_by_entry(prepared_data[:2000],yhat[:2000])

In [ ]:
errors = np.array(errors)

In [ ]:
def anomalias(errors,thresh):
    std = errors.std()
    media = errors.mean()
    ret = []
    for i in range(0,errors.shape[0]):
        if(errors[i] > media + thresh*std):
            ret.append(i)
    return(ret)

In [11]:
### outtliers
er = np.array([2,5,16,17,17,17,6,17,18,16,17,18,16,17])

In [12]:
er.mean()

14.214285714285714

In [13]:
er.std()

5.253278859484827

In [14]:
er.mean() + 2*er.std()

24.720843433255368

In [15]:
er.mean() - 2*er.std()

3.707727995316059

In [ ]:
errors.reshape(-1,1).T.shape

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(errors.reshape(-1,1))
plt.show()